function accuracy1 = f_svm_decoder(predictors, response, tt)

%%
% SVMModel = fitcsvm(...
%     predictors, ...
%     response, ...
%     'KernelFunction', 'gaussian', ...     % 'KernelFunction', 'polynomial' 'gaussian'
%     'PolynomialOrder', [], ...               % 2
%     'KernelScale', 7.1, ...              % auto fine = 1.8 medium= 7.1 coarse = 28
%     'BoxConstraint', 1, ...
%     'Standardize', true, ...
%     'ClassNames', tt');

template = templateSVM(...
    'KernelFunction', 'gaussian', ...
    'PolynomialOrder', [], ...
    'KernelScale', 10, ...
    'BoxConstraint', 1, ...
    'Standardize', true);
SVMModel = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', tt');

%% cross validation 
model1 = SVMModel;

partitionedModel = crossval(model1, 'KFold', 5);

%[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
accuracy1 = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');


end